### ISSUE TITLE
app starts and disappears when i execute "cordova windows run"

### ISSUE THREAD

**Issue by myusrn** [AzureADSamples/NativeClient-GraphAPI-Cordova#1]
the app starts and disappears when i execute "cordova windows run" and if i launch from winkey | all apps | hellocordova.

when i got to step 6 the "cordova plugin add com.ionic.keyboard" command returned "Error: Failed to fetch plugin com.ionic.keyboard via registry." and so i used "cordova plugin add ionic-plugin-keyboard" instead which did succeed.   Not sure if that was the relevant fix for that error or not.

event viewer | application log entry ias the following, any suggestions on what i did wrong?

---

Fault bucket 133284001091, type 5
Event Name: WWAJSE
Response: Not available
Cab Id: 0

Problem signature:
P1: io.cordova.hellocordova_0.0.1.0_neutral__h35559jr9hy9m
P2: io.cordova.hellocordova
P3: 7d80
P4: 5
P5: ms-appx://io.cordova.hellocordova/www/js/app.js
P6: 15_19
P7: 
P8: 
P9: 
P10: 

Attached files:
ErrorInfo.8156.12364.txt
C:\Program Files\WindowsApps\io.cordova.hellocordova_0.0.1.0_neutral__h35559jr9hy9m\AppXManifest.xml
<userprofile>\AppData\Local\Temp\WERAD33.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\NonCritical_io.cordova.hello_e1e5e193adac462a6155df77294ef27b91fce5_00000000_1218b1e6

Analysis symbol: 
Rechecking for solution: 0
Report Id: acfa7a4f-ca19-11e5-b356-0050b67d8b10
Report Status: 4104
Hashed bucket: 1dd78caaff0eca6d24203a81cce7a12a

**Comment by bkelley13** [comment]
I'm seeing this too, did you find a solution?

**Comment by myusrn** [comment]
the "cordova plugin add ionic-plugin-keyboard" seems to still be the work around for getting that plugin enable
